// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Button(Props) {
  var onClick = Props.onClick;
  var children = Props.children;
  return React.createElement("button", {
              className: "border rounded px-1 min-w-[32px] w-full text-center",
              onClick: onClick
            }, children);
}

var make = Button;

export {
  make ,
  Button ,
}
/* react Not a pure module */
