// Generated by ReScript, PLEASE EDIT WITH CARE

import * as H1 from "./H1.mjs";
import * as Game from "./Game.mjs";
import * as React from "react";

function $$default(param) {
  return React.createElement("div", {
              className: "container mx-auto"
            }, React.createElement(H1.make, {
                  children: "2048"
                }), React.createElement(Game.make, {}), React.createElement("footer", {
                  className: "mt-16"
                }, React.createElement("a", {
                      className: "text-blue-700 underline",
                      href: "https://github.com/nino/rescript-2048/"
                    }, "https://github.com/nino/rescript-2048/")));
}

export {
  $$default ,
  $$default as default,
}
/* H1 Not a pure module */
