// Generated by ReScript, PLEASE EDIT WITH CARE

import * as H1 from "./H1.mjs";
import * as Game from "./Game.mjs";
import * as React from "react";

function $$default(param) {
  return React.createElement("div", {
              className: "container mx-auto"
            }, React.createElement(H1.make, {
                  children: "2048"
                }), React.createElement(Game.make, {}));
}

export {
  $$default ,
  $$default as default,
}
/* H1 Not a pure module */
