// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Input(Props) {
  var label = Props.label;
  var value = Props.value;
  var onChange = Props.onChange;
  var type_ = Props.type_;
  return React.createElement("div", {
              className: "m-1"
            }, React.createElement("label", {
                  className: "flex flex-col"
                }, label, React.createElement("input", {
                      className: "border-black border",
                      type: type_,
                      value: value,
                      onChange: onChange
                    })));
}

var make = Input;

export {
  make ,
}
/* react Not a pure module */
