// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function Link$1(Props) {
  var href = Props.href;
  var children = Props.children;
  return React.createElement(Link, {
              href: href,
              children: React.createElement("a", {
                    className: "text-blue-600 underline"
                  }, children)
            });
}

var make = Link$1;

export {
  make ,
}
/* react Not a pure module */
