// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function P(Props) {
  var children = Props.children;
  return React.createElement("p", {
              className: "m-1"
            }, children);
}

var make = P;

export {
  make ,
}
/* react Not a pure module */
