// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function MainLayout(Props) {
  var children = Props.children;
  return React.createElement("div", undefined, children);
}

var make = MainLayout;

export {
  make ,
}
/* react Not a pure module */
